// components/tags.jsx
import Link from "next/link";

export default function Tags({ tag }) {
  return (
    <Link href={`/tag/${tag.replace(/ /g, "-")}`}>
      <button className="border border-gray-200 p-1">
        <p className="font-OpenSans text-xs text-slate-400 hover:text-gray-600 ">
          {tag}
        </p>
      </button>
    </Link>
  );
}

// src/routes/blog/[slug]/tags.svelte
<script lang="ts">
	import Button from '$lib/components/ui/button/button.svelte';

	export let tag: String;
</script>

<a href={`/tag/${tag.replace(/ /g, '-')}`}>
	<Button variant="outline" class="p-2">
		<p class="font-OpenSans text-xs text-slate-400 hover:text-gray-600">
			&num;{tag}
		</p>
	</Button>
</a>
